version: 2

jobs:
  checkout:
    working_directory: ~/repo
    docker:
      - image: alpine/git:latest
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - ./repo

  build:
    working_directory: ~/repo
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: cache-{{ checksum "project.clj" }}
      - run:
          name: Install dependencies
          command: lein deps
      - save_cache:
          key: cache-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

  unit-test:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.7-browsers
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: run unit tests
          command: pipenv run pytest -k unit

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - unit-test:
          requires:
            - build
