version: 2

jobs:
  checkout:
    working_directory: ~/repo
    docker:
      - image: alpine/git:latest
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - ./repo

  build:
    working_directory: ~/repo
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: cache-{{ checksum "project.clj" }}
      - run:
          name: Install dependencies
          command: lein deps
      - run:
          name: list folders
          command: ls -all ~/ && ls -all ~/repo
      - save_cache:
          key: cache-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - persist_to_workspace:
          root: ~/
          paths:
            - ./

  backend-test:
    working_directory: ~/repo
    docker:
        - image: circleci/clojure:openjdk-11-lein-2.9.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: run backend tests
          command: lein run test

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - backend-test:
          requires:
            - build
